### ISSUE TITLE
Upload a file to an existing table for upsert

### ISSUE THREAD

**Issue by rufuspollock** [okfn/webstore#24]
I want to upload a csv file to an existing table and specify unique cols for upsert.

Can currently do this but this creates a new table AFAICT:

```
 curl --data-binary @myfile.csv -i -H "Content-type: text/csv" http://{host}/{user-name}/{db-name}?table={table-name}}
```

Question: how does type determination happen when uploading csv files or the like?

**Comment by pudo** [comment]
At the moment no types are detected for incoming CSV data, everything is assumed to be unicode text. While it would be very interesting to support typed columns, this is not trivial for CSV and would require us to use something like messytables to type-guess the columns. 

As for the other part of the ticket: 

```
curl --data-binary @myfile.csv -i -H "Content-type: text/csv" http://{host}/{user-name}/{db-name}/{table-name}}?unique=foo&unique=bar
```

**Comment by pudo** [comment]
Closing as there is no action here.

**Comment by rufuspollock** [comment]
I think you are missing the -X PUT in your instructions ;-) but otherwise agree this is obsolete / done.

**Comment by pudo** [comment]
Added it here: https://github.com/okfn/webstore/commit/0302da9bfaa3dd754316b44bd958079adba104d0#L0R197
