### ISSUE TITLE
Not allowed - in database names

### ISSUE THREAD

**Issue by rufuspollock** [okfn/webstore#30]
It appears one is not allowed '-' in database names (wonder what other characters are not allowed -- is this documented somewhere?). I'd propose allowing "-_." in db names unless there is a specific reason not to.

While tracking down this problem also came across issue of poor / not very descriptive error message. E.g. while trying to upload a csv file to db named 'gold-prices' got the error:

{"message": "Invalid DB: gold-prices", "state": "error"}

This in no way indicated that problem was with the name of the database.

**Comment by johnglover** [comment]
I'm not sure that it's documented, you're currently allowed '_' but not '-', but yes I agree.

**Comment by pudo** [comment]
Fixed in code now. Still not allowing dash as a prefix.

**Comment by rufuspollock** [comment]
Agree that we should not allow '.', '_' or '-' as a prefix (i guess we could allow '_' as prefix but don't like it ...)

**Comment by pudo** [comment]
Hm, we have this convention that _xxx is some kind of "opcode" - I'd like to enforce that everywhere.

**Comment by rufuspollock** [comment]
Agreed -- i said i'd prefer _not_ to have anything starting in '_-.' but could stomach '_' if really wanted but sounds like it isn't :-)
