### ISSUE TITLE
Attempt to upload csv file to existing table results in error

### ISSUE THREAD

**Issue by rufuspollock** [okfn/webstore#31]
Tried a re-upload as per docs using unique attribute:

<pre>
curl --data-binary @data.csv -u ... -i -H "Content-type: text/csv" http://webstore.thedatahub.org/rufuspollock/gold_prices/data?unique=date
</pre>

But received this error message:

<pre>
HTTP/1.1 100 Continue

HTTP/1.1 409 CONFLICT
Date: Sun, 28 Aug 2011 17:03:19 GMT
Server: Apache/2.2.15 (Debian)
Location: http://webstore.thedatahub.org/rufuspollock/gold_prices/data
Content-Length: 100
Content-Type: application/json

{"url": "/rufuspollock/gold_prices/data", "message": "Table already exists: data", "state": "error"}
</pre>

**Comment by pudo** [comment]
You must use the PUT operation to update table data (i.e. curl -XPUT). POST is used only for table creation and will yield an error on existing tables.

**Comment by rufuspollock** [comment]
If this is so then the docs are buggy because the example in the docs does not use -X PUT ...
