### ISSUE TITLE
New default result format for json

### ISSUE THREAD

**Issue by rufuspollock** [okfn/webstore#40]
There are issues with current default json result format (no way to get ordered columns, no way to add other things like count). Options for format:
- { keys: [column_names], data: [ [...] ] } - jsontuples
- [ { col: val, col: val, ... } ] - current default return .json
- { keys: [columns], data: [ {col: val, col:val}, ... ] }

NB: both 1 and 3 would allow for other keys such as count (aka numFound, total_rows)  (cd #29).

Going forward we should switch to option (3) and make that the default for .json. If other options are wanted we can open more tickets.

In addition it may be desirable to expand column info from just a name to include things like type e.g.:
- columns: [ {name: ..., type: ..., ...} ]
## Spec

<pre>
Query result 
{
  fields: [ list of field items ],
  data: [ {field-name: value}, ... ]
  count: ...
}

field item:
{
    name: ...
    type: ...
}
</pre>

## Count field
- Named: count. See #29.
## References
- HtSQL: http://htsql.org/blog/discuss-headers.html
- CouchDB: total_rows (not really count),

**Comment by kindly** [comment]
This has been completed in commit #928ff02004420f431918d94d974f32efd2971384.   We are not adding the type information yet to the field list as a little thinking about what theses should be should be done first.
